#!/bin/sh

export DESKTOP_SESSION=lxqt
export XDG_CURRENT_DESKTOP=LXQt
export XDG_MENU_PREFIX=lxqt-
export XDG_SESSION_TYPE=x11
export QT_QPA_PLATFORM=xcb
export QT_QPA_PLATFORMTHEME=qt5ct

# Ergänzung für bessere Schriftdarstellung in RDP
#export XCURSOR_PATH=/usr/share/icons
#export XDG_DATA_DIRS=/usr/local/share:/usr/share:$HOME/.local/share
#export FREETYPE_PROPERTIES="truetype:interpreter-version=40"

# Software Rendering (VDI)
export LIBGL_ALWAYS_SOFTWARE=1
export GALLIUM_DRIVER=llvmpipe
export QT_XCB_GL_INTEGRATION=none

# Runtime dir
#export XDG_RUNTIME_DIR=/run/user/$(id -u)
export XDG_RUNTIME_DIR="/tmp/runtime-$(id -u)"
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR"
chown $(id -u):$(id -g) "$XDG_RUNTIME_DIR"


# FIX: Verhindert, dass Pipewire Realtime-Priorität erzwingen will (was im Container scheitert)
export PIPEWIRE_RUNTIME_DIR="$XDG_RUNTIME_DIR"
export PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native

#set to Regional to no change - if LANG empty keyboard no longer correct ch
#export LANG='' #LANGUAGE=''

#openbox-session & #ich habe xfwm4
xfwm4 --compositor=off &
sleep 1


#wireplumber & pipewire
start_sound() {
	# Start Pipewire im Hintergrund (User-Level)
	pkill -u "$USER" -fx /usr/bin/pipewire-pulse 1>/dev/null 2>&1
	pkill -u "$USER" -fx /usr/bin/wireplumber 1>/dev/null 2>&1
	pkill -u "$USER" -fx /usr/bin/pipewire 1>/dev/null 2>&1
	pkill -u "$USER" 'pw-cli' >/dev/null 2>&1

	/usr/bin/pipewire &
	# wait for pipewire to start before attempting to start related daemons
	local COUNT=0
    local MAX_RETRIES=10
    while [ -z "$(pgrep -u "$USER" -x pipewire)" ] && [ $COUNT -lt $MAX_RETRIES ]; do
        echo "Warte auf Pipewire ($((COUNT+1))/$MAX_RETRIES)..."
        sleep 1
        COUNT=$((COUNT + 1))
    done

	/usr/bin/wireplumber &
	/usr/bin/pipewire-pulse &
	sleep 1

	#Angepasst auf 1024
	#original von https://github.com/neutrinolabs/pipewire-module-xrdp/tree/devel
	local file="/usr/local/libexec/pipewire-module-xrdp/load_pw_modules.sh"
	if [ -f "$file" ]; then
    	$file
	fi

}
# Sound-Start in den Hintergrund schicken
start_sound


#exec lxqt-session
exec startlxqt
